/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Int,
});

export const idlService = IDL.Service({
  'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteArticle' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'publishArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Int,
  });
  
  return IDL.Service({
    'changePassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteArticle' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'publishArticle' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };